# Generated by Django 2.2.4 on 2019-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190808_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(),
        ),
    ]
